### ISSUE TITLE
Mime type handling 

### ISSUE THREAD

**Issue by abbysmal** [Engil/Canopy#2]
Currently, Canopy don't send any mime-type informations, would be nice to have it somehow.

**Comment by voila** [comment]
What have you got in mind ? Do you mean adding a Content-Type header [here](https://github.com/Engil/Canopy/blob/master/canopy_main.ml#L124) for instance ?

**Comment by abbysmal** [comment]
Yeah, there is a few more places where it's needed (like for the static files) but the question would be how to retrieve the mime-type information.
At the moment, we serve fonts, CSS files, JS and Html (and probably at some point images.).
I'm not really sure how to handle that and send the proper content-types.

**Comment by voila** [comment]
One way to do this would be to map from file extensions to Mime types like [Apache](https://httpd.apache.org/docs/2.4/mod/mod_mime.html) seems to do...

**Comment by samoht** [comment]
Or use https://github.com/mirage/ocaml-magic-mime

It is already used by various other MirageOS-powered websites (look at [mirage-seal](https://github.com/mirage/mirage-seal/blob/master/static/dispatch.ml#L29-L30) for instance)

**Comment by hannesm** [comment]
is fixed now :) and can be closed
