### ISSUE TITLE
HTTP last modified header

### ISSUE THREAD

**Issue by hannesm** [Engil/Canopy#25]
would be great if Canopy would emit [Last-Modified](https://tools.ietf.org/html/rfc2616#section-14.29) headers (and respect If-Modified-Since), thus subsequent requests would not need to fetch all dependent resources (CSS/JS/..). For static pages, this could be the startup time of Canopy, for articles there is already a `last_updated` field :)

**Comment by voila** [comment]
This sounds like fun!

How would you get hold of the unikernel startup time ? Via clock in Main.start ?
How should this value be make its way to the dispatcher code?

Also, where can we inspect the HTTP headers of the request (to extract If-Modified-Since) ?
I can't find anything about the request in module Main...

**Comment by avsm** [comment]
would be better to extend crunch to store mtime; unikernel startup time should not invalidate the http content cache

also could use Etag headers...

**Comment by hannesm** [comment]
@voila `CLOCK.time ()` gets the time (I'd do that in `Canopy_main.start`), I'd convert it to a `Ptime.t` value and pass it to the dispatcher...

the `Canopy_dispatch.dispatcher` currently receives the `uri` of the request (look in `create`), which would need to get the full `request` (I've some changes there to get a HTTP access log [here](https://github.com/hannesm/Canopy/commit/f04256bed18edf6e256afe30c079262be1914aa0) which might explain a bit what I mean).

it might be easier to create `Etag` headers and parse `If-None-Match` headers (esp since the time format in HTTP is different from Ptime's supported RFC3339)...

**Comment by hannesm** [comment]
@avsm I think patching up crunch is not helpful in the long run, it works good for small things, but we need sth more reliable (such as an ELF section ;)

and file mtime vs startup time of the kernel -- well, I tend to not restart my kernels too often, and consider this negligible...

**Comment by hannesm** [comment]
done now :D
