### ISSUE TITLE
[Feature request] Timestamp in posts listing

### ISSUE THREAD

**Issue by reynir** [Engil/Canopy#28]
Hi,

I think it could be useful to have the post timestamp in the posts listing, especially for people who have not kept up with the Mirage progress.

http://canopy.mirage.io/Posts

Skimming through the source I can't see where the Posts listing is made.

**Comment by abbysmal** [comment]
Should be possible to add a timestamp in each entry.

The Posts listing is generated here: https://github.com/Engil/Canopy/blob/master/canopy_dispatch.ml#L77
If the dispatcher find no article at a given URL, it tries to load a directory (here, the Posts directory) and render a listing page with all entries in this directory.

And the HTML chunks for each entries are generated using this function:
https://github.com/Engil/Canopy/blob/master/canopy_article.ml#L45

And this is pretty much everything. :)

I will do it probably tomorrow, however one good thing is that posts in listings are ordered by timestamp already, the first one being the most recent. :)

Thank you for your feedback!
