### ISSUE TITLE
last updated is after published!?

### ISSUE THREAD

**Issue by hannesm** [Engil/Canopy#33]
how can this happen: `Published: 2016-04-24 (last updated: 2016-04-22)`?  (on https://hannes.nqsb.io/Posts/nqsbWebsite [when there was only a single commit touching (adding) the post, no updates yet])...

**Comment by abbysmal** [comment]
This is weird and related to the clunky implementation of last_updated_commit.
This implementation was slow and I wasn't sure it was correct. I wrote some weeks ago a less clunky implementation, but wasn't sure it was 100% correct. (tested it quickly on huge repo with weird merges, like GHC, and it looked fine.)
At least it fixes your problem :)
![capture d ecran 2016-04-25 a 10 48 44](https://cloud.githubusercontent.com/assets/146049/14780225/e82c76b8-0ad3-11e6-9aed-04132a0a0075.png)
