### ISSUE TITLE
Moving from Hashtable to Map.Make

### ISSUE THREAD

**Issue by abbysmal** [Engil/Canopy#36]
As discussed in #30, it would be nice to move to Map.Make instead of using Hashtable.
I don't seed any major problem in doing so, I will do either today or tomorrow.

I think it should be pretty straightforward, the main problem being that we used a single hashtable before and we'll probably need to insert a reference instead… If you have better solutions, feedbacks welcome as usual. :)

**Comment by voila** [comment]
I can have a go at this, if you want... In fact I am nearly done. I just need to do a few tests

**Comment by abbysmal** [comment]
@voila this is great! Thank you. :)
