### ISSUE TITLE
links point to the slightly wrong location

### ISSUE THREAD

**Issue by hannesm** [Engil/Canopy#4]
on a given post (such as http://canopy.mirage.io/Posts/Notes), the links in the top line point to http://canopy.mirage.io/Posts/Index http://canopy.mirage.io/Posts/Posts http://canopy.mirage.io/Posts/Wiki (thus, a superfluous `Posts`)...

**Comment by abbysmal** [comment]
Ooops, I changed a few things this week end regarding HTML generation. Thank you!

**Comment by hannesm** [comment]
that was fast, thanks! :)
