### ISSUE TITLE
Default color scheme for code is hard to read

### ISSUE THREAD

**Issue by Drup** [Engil/Canopy#50]
Example: https://hannes.nqsb.io/Posts/Functoria

The code is light grey on light yellow with bold yellow keywords, my eyes really can't handle that kind of low contrast. Moving to black text would help a lot, but using a better code coloration engine/them would be nice.

In general, I advise the use of http://khan.github.io/tota11y

**Comment by abbysmal** [comment]
Yup, I understand.
I guess changing the theme would be the simplest, since we use highlight.js.
The available themes are shown on their homepage, if someone want to pick one to use as a default, please do. :-) https://highlightjs.org/

I will try tota11y, it looks amazing, thank you! :)

**Comment by hannesm** [comment]
what about Grayscale? simple and not colored... or maybe Sunburst?

**Comment by Drup** [comment]
I find both decently readable.

**Comment by hannesm** [comment]
i switched to grayscale on my canopy instance https://hannes.nqsb.io/Posts/Functoria
