### ISSUE TITLE
exception in accept

### ISSUE THREAD

**Issue by hannesm** [Engil/Canopy#9]
just got this...

```
Repository pulled
(closed connection 434)
Fatal error: exception Unix.Unix_error(Unix.ECONNABORTED, "accept", "")
Called from file "src/unix/lwt_unix.ml", line 487, characters 13-24
```

**Comment by abbysmal** [comment]
There is some bugs going on when not using Lwt_unix compiled against libev, haven't had the time to explore that yet but I usually have a quickfix.
If your system support it, installing conf-libev and then recompiling lwt should be enough.
Sorry about that!

**Comment by hannesm** [comment]
never saw it again, might have been a spurious https://github.com/ocsigen/lwt/issues/222 (fixed with https://github.com/mirage/mirage-http/pull/23), also now I'm running canopy on Xen, thus closing this..
